name: My GitHub Projects Automations
description: Automate my GitHub Projects
inputs:
    project-owner:
        required: false
        description: "The owner of the project"
    project-number:
        required: true
        description: "The number of the project. Get this from the URL."
    github-token:
        required: true
        description: "A GitHub personal access token with write access to the project"
    field-names:
        required: false
        description: A comma-separated list of single select fields
    field-values:
        required: false
        description: A comma-separated list of single select options 
runs:
    using: node16
    main: dist/index.js