name: CD
on:
    workflow_dispatch:
        inputs:
            bump:
                description: Bump (The type of semantic version increment to make)
                type: choice
                options:
                    - patch
                    - minor
                    - major

jobs:
    bump_version:
        name: Bump version and write it to package.json
        runs-on: ubuntu-latest
        outputs:
            version_tag: v${{ steps.bump_version.outputs.version_tag }}
        steps:
            - name: Checkout code
              uses: actions/checkout@v3
            - name: Bump version
              id: bump_version
              uses: zwaldowski/semver-release-action@v3
              with:
                  bump: ${{ inputs.bump }}
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  dry_run: true
            - name: Read version from package.json
              id: read_package_json_version
              run: echo "package_json_version=$(awk '/version/{gsub(/("|",)/,"",$2);print $2}' package.json)" >> $GITHUB_OUTPUT
            - name: Write version to package.json
              if: ${{ steps.read_package_json_version.outputs.package_json_version != steps.bump_version.outputs.version_tag }}
              run: "sed -i'' -E 's/\"version\": \"[0-9]*\\.[0-9]*\\.[0-9]*\"/\"version\": \"${{ steps.bump_version.outputs.version_tag }}\"/g' package.json"
            - name: Commit and push change
              if: ${{ steps.read_package_json_version.outputs.package_json_version != steps.bump_version.outputs.version_tag }}
              run: |
                  git config --global user.name 'SH1RL0CK'
                  git config --global user.email '50455686+SH1RL0CK@users.noreply.github.com'
                  git commit -am "write new version to package.json"
                  git push

    create_release:
        name: Create release
        runs-on: ubuntu-latest
        needs: bump_version
        steps:
            - name: Checkout code
              uses: actions/checkout@v3
            - name: Push tag
              uses: anothrNick/github-tag-action@v1
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  CUSTOM_TAG: ${{ needs.bump_version.outputs.version_tag }}
            - name: Create release
              id: create_release
              uses: actions/create-release@v1
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                  tag_name: ${{ needs.bump_version.outputs.version_tag}}
                  release_name: Release ${{ needs.bump_version.outputs.version_tag }}
                  body_path: ./RELEASE_BODY.md
