name: My Github Project Automation

on:
  issues:
    types:
      - opened
      - assigned
  pull_request:
    types:
      - opened
    branches:
      - main 

jobs:
  project_automation:
    runs-on: ubuntu-latest
    name: Automate my GitHub project
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Automate my GitHub project
        uses: ./ 
        with:
            project-number: 30 
            github-token: ${{ secrets.PROJECT_AUTOMATION_PAT }}